export const state = () => ({
  GroupOptions: [
    {
      img: "grocery.png",
      title: "Grocery",
    },
    {
      img: "burgers.png",
      title: "Burgers",
    },
    {
      img: "chicken-wings.png",
      title: "Chicken",
    },
    {
      img: "pizza.png",
      title: "Pizza",
    },
    {
      img: "Chinese.png",
      title: "Chinese",
    },
    {
      img: "sushi.png",
      title: "Sushi",
    },
    {
      img: "Asian.png",
      title: "Asian",
    },
    {
      img: "Italian.png",
      title: "Italian",
    },
    {
      img: "dessert.png",
      title: "Dessert",
    },
    {
      img: "thai.png",
      title: "Thai",
    },
    {
      img: "Indian.png",
      title: "Indian",
    },
    {
      img: "healthy.png",
      title: "Healthy",
    },
    {
      img: "breakfast.png",
      title: "Breakfast",
    },
  ],
  Neighbourhood: [
    {
      deliveryFee: "£0.99 delivery",
      duration: "25-40",
      restaurantName: "Deliveroo HOP",
      rating: "4.7 Excellent",
      ratingCount: 500,
      locationDistance: "2.3 miles away",
      restaurantLogo: "deliveroohop.jpeg",
    },
    {
      deliveryFee: "£1.99 delivery",
      duration: "25-35",
      restaurantName: "Five Guys - Burger and Fries",
      rating: "4.6 Excellent",
      ratingCount: 500,
      locationDistance: "1.3 miles away",
      restaurantLogo: "FiveGuys.jpg",
    },
    {
      deliveryFee: "£1.99 delivery",
      duration: "25-40",
      restaurantName: "Poke Shack - Kensington",
      rating: "4.7 Excellent",
      ratingCount: 500,
      locationDistance: "Nearby",
      restaurantLogo: "PokeShark.jpeg",
    },
    {
      deliveryFee: "Get 50% off",
      duration: "35-45",
      restaurantName: "Good BBQ",
      rating: "4.3 Good",
      ratingCount: 450,
      locationDistance: "1.3 miles away",
      restaurantLogo: "GoodBBQ.jpeg",
    },
    {
      deliveryFee: "£2.49 delivery",
      duration: "30-40",
      restaurantName: "Chicken Shop",
      rating: "4.5 Excellent",
      ratingCount: 500,
      locationDistance: "Nearby",
      restaurantLogo: "ChickenShop.jpeg",
    },
  ],
  Featured: [
    {
      deliveryFee: "£0.99 delivery",
      duration: "25-40",
      restaurantName: "Burger King",
      rating: "4.7 Excellent",
      ratingCount: 500,
      locationDistance: "2.3 miles away",
      restaurantLogo: "BurgerKing.jpg",
    },
    {
      deliveryFee: "£1.99 delivery",
      duration: "15-20",
      restaurantName: "Chiptole Mexican Grill",
      rating: "4.5 Excellent",
      ratingCount: 250,
      locationDistance: "Nearby",
      restaurantLogo: "ChiptoleMexicanGrill.jpeg",
    },
    {
      deliveryFee: "£0.99 delivery",
      duration: "25-40",
      restaurantName: "Coco Di Mama",
      rating: "4.7 Excellent",
      ratingCount: 500,
      locationDistance: "3 miles away",
      restaurantLogo: "CocoDiMama.jpeg",
    },
    {
      deliveryFee: "£0.99 delivery",
      duration: "15-20",
      restaurantName: "Wagamama",
      rating: "4.8 Excellent",
      ratingCount: 500,
      locationDistance: "2 miles away",
      restaurantLogo: "Wagamama.png",
    },
    {
      deliveryFee: "£2.29 delivery",
      duration: "20-25",
      restaurantName: "FireAway Pizza",
      rating: "4.7 Excellent",
      ratingCount: 500,
      locationDistance: "2.6 miles away",
      restaurantLogo: "FireawayPizza.jpeg",
    },
    {
      deliveryFee: "£1.99 delivery",
      duration: "25-40",
      restaurantName: "Gourmet Burger Kitchen",
      rating: "4.5 Excellent",
      ratingCount: 450,
      locationDistance: "2.1 miles away",
      restaurantLogo: "GourmetBurgerKitchen.jpeg",
    },
    {
      deliveryFee: "£0.99 delivery",
      duration: "25-40",
      restaurantName: "Island Poke",
      rating: "4.3 Excellent",
      ratingCount: 300,
      locationDistance: "2.3 miles away",
      restaurantLogo: "IslandPoke.jpeg",
    },
  ],
  PopularGrid: [
    {
      deliveryFee: "£0.99 delivery",
      duration: "25-40",
      restaurantName: "Burger King",
      rating: "4.7 Excellent",
      ratingCount: 500,
      locationDistance: "2.3 miles away",
      restaurantLogo: "BurgerKing.jpg",
    },
    {
      deliveryFee: "£1.99 delivery",
      duration: "15-20",
      restaurantName: "Chiptole Mexican Grill",
      rating: "4.5 Excellent",
      ratingCount: 250,
      locationDistance: "Nearby",
      restaurantLogo: "ChiptoleMexicanGrill.jpeg",
    },
    {
      deliveryFee: "£0.99 delivery",
      duration: "25-40",
      restaurantName: "Coco Di Mama",
      rating: "4.7 Excellent",
      ratingCount: 500,
      locationDistance: "3 miles away",
      restaurantLogo: "CocoDiMama.jpeg",
    },
    {
      deliveryFee: "£0.99 delivery",
      duration: "15-20",
      restaurantName: "Wagamama",
      rating: "4.8 Excellent",
      ratingCount: 500,
      locationDistance: "2 miles away",
      restaurantLogo: "Wagamama.png",
    },
    {
      deliveryFee: "£2.29 delivery",
      duration: "20-25",
      restaurantName: "FireAway Pizza",
      rating: "4.7 Excellent",
      ratingCount: 500,
      locationDistance: "2.6 miles away",
      restaurantLogo: "FireawayPizza.jpeg",
    },
    {
      deliveryFee: "£1.99 delivery",
      duration: "25-40",
      restaurantName: "Gourmet Burger Kitchen",
      rating: "4.5 Excellent",
      ratingCount: 450,
      locationDistance: "2.1 miles away",
      restaurantLogo: "GourmetBurgerKitchen.jpeg",
    },
    {
      deliveryFee: "£0.99 delivery",
      duration: "25-40",
      restaurantName: "Island Poke",
      rating: "4.3 Excellent",
      ratingCount: 300,
      locationDistance: "2.3 miles away",
      restaurantLogo: "IslandPoke.jpeg",
    },
  ],
});
